# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ole/Dokumente/cs50/Final_Project/weather_cli

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ole/Dokumente/cs50/Final_Project/weather_cli

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ole/Dokumente/cs50/Final_Project/weather_cli/CMakeFiles /home/ole/Dokumente/cs50/Final_Project/weather_cli//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ole/Dokumente/cs50/Final_Project/weather_cli/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named weather_cli

# Build rule for target.
weather_cli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 weather_cli
.PHONY : weather_cli

# fast build rule for target.
weather_cli/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/weather_cli.dir/build.make CMakeFiles/weather_cli.dir/build
.PHONY : weather_cli/fast

src/cJSON.o: src/cJSON.c.o
.PHONY : src/cJSON.o

# target to build an object file
src/cJSON.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/weather_cli.dir/build.make CMakeFiles/weather_cli.dir/src/cJSON.c.o
.PHONY : src/cJSON.c.o

src/cJSON.i: src/cJSON.c.i
.PHONY : src/cJSON.i

# target to preprocess a source file
src/cJSON.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/weather_cli.dir/build.make CMakeFiles/weather_cli.dir/src/cJSON.c.i
.PHONY : src/cJSON.c.i

src/cJSON.s: src/cJSON.c.s
.PHONY : src/cJSON.s

# target to generate assembly for a file
src/cJSON.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/weather_cli.dir/build.make CMakeFiles/weather_cli.dir/src/cJSON.c.s
.PHONY : src/cJSON.c.s

src/image_to_ascii.o: src/image_to_ascii.c.o
.PHONY : src/image_to_ascii.o

# target to build an object file
src/image_to_ascii.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/weather_cli.dir/build.make CMakeFiles/weather_cli.dir/src/image_to_ascii.c.o
.PHONY : src/image_to_ascii.c.o

src/image_to_ascii.i: src/image_to_ascii.c.i
.PHONY : src/image_to_ascii.i

# target to preprocess a source file
src/image_to_ascii.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/weather_cli.dir/build.make CMakeFiles/weather_cli.dir/src/image_to_ascii.c.i
.PHONY : src/image_to_ascii.c.i

src/image_to_ascii.s: src/image_to_ascii.c.s
.PHONY : src/image_to_ascii.s

# target to generate assembly for a file
src/image_to_ascii.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/weather_cli.dir/build.make CMakeFiles/weather_cli.dir/src/image_to_ascii.c.s
.PHONY : src/image_to_ascii.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/weather_cli.dir/build.make CMakeFiles/weather_cli.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/weather_cli.dir/build.make CMakeFiles/weather_cli.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/weather_cli.dir/build.make CMakeFiles/weather_cli.dir/src/main.c.s
.PHONY : src/main.c.s

src/terminal_support.o: src/terminal_support.c.o
.PHONY : src/terminal_support.o

# target to build an object file
src/terminal_support.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/weather_cli.dir/build.make CMakeFiles/weather_cli.dir/src/terminal_support.c.o
.PHONY : src/terminal_support.c.o

src/terminal_support.i: src/terminal_support.c.i
.PHONY : src/terminal_support.i

# target to preprocess a source file
src/terminal_support.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/weather_cli.dir/build.make CMakeFiles/weather_cli.dir/src/terminal_support.c.i
.PHONY : src/terminal_support.c.i

src/terminal_support.s: src/terminal_support.c.s
.PHONY : src/terminal_support.s

# target to generate assembly for a file
src/terminal_support.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/weather_cli.dir/build.make CMakeFiles/weather_cli.dir/src/terminal_support.c.s
.PHONY : src/terminal_support.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... weather_cli"
	@echo "... src/cJSON.o"
	@echo "... src/cJSON.i"
	@echo "... src/cJSON.s"
	@echo "... src/image_to_ascii.o"
	@echo "... src/image_to_ascii.i"
	@echo "... src/image_to_ascii.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/terminal_support.o"
	@echo "... src/terminal_support.i"
	@echo "... src/terminal_support.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

